[package]
org = "ballerinax"
name = "financial.iso20022ToSwiftmt"
version = "0.9.0"
distribution = "2201.10.1"
authors=["Ballerina"]
keywords=["Financial", "SWIFT MT", "ISO 20022", "Conversion"]
repository="https://github.com/ballerina-platform/module-ballerinax-financial.iso20022-to-swiftmt"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
